/**
 * Shared constants used across the application
 */

export const APP_CONSTANTS = {
  NAME: 'communication-server-mcp',
  VERSION: '2.3.9',
  DESCRIPTION: 'Advanced MCP communication server for AI agents',
  AUTHOR: 'Communication Server Team'
} as const;

export const DATABASE_CONSTANTS = {
  DEFAULT_PATH: '~/.communication-server',
  DEFAULT_FILENAME: 'communication.db',
  MAX_CONNECTIONS: 10,
  TIMEOUT: 30000,
  WAL_MODE: true,
  MIGRATION_VERSION: 1,
  CONNECTION_TIMEOUT: 5000,
  QUERY_TIMEOUT: 30000,
  VACUUM_INTERVAL: 24 * 60 * 60 * 1000 // 24 hours
} as const;

export const SECURITY_CONSTANTS = {
  ENCRYPTION_ALGORITHM: 'aes-256-gcm',
  SIGNING_ALGORITHM: 'hmac-sha256',
  KEY_LENGTH: 32,
  IV_LENGTH: 16,
  SALT_LENGTH: 64,
  KEY_ROTATION_INTERVAL: 24 * 60 * 60 * 1000, // 24 hours
  SESSION_TIMEOUT: 30 * 60 * 1000, // 30 minutes
  MAX_SESSION_DURATION: 240 * 60 * 1000 // 4 hours
} as const;

export const CACHE_CONSTANTS = {
  DEFAULT_MAX_SIZE: 1000,
  DEFAULT_TTL: 300000, // 5 minutes
  DEFAULT_EVICTION_POLICY: 'LRU',
  PERSISTENCE_INTERVAL: 60000, // 1 minute
  COMPRESSION_THRESHOLD: 1024 // 1KB
} as const;

export const EVENT_CONSTANTS = {
  MAX_HANDLERS: 100,
  MAX_QUEUE_SIZE: 10000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
  BATCH_SIZE: 100,
  FLUSH_INTERVAL: 5000 // 5 seconds
} as const;

export const LOGGING_CONSTANTS = {
  DEFAULT_LEVEL: 'INFO',
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  MAX_FILES: 5,
  BATCH_SIZE: 100,
  FLUSH_INTERVAL: 5000, // 5 seconds
  TRACE_RETENTION: 24 * 60 * 60 * 1000 // 24 hours
} as const;

export const MESSAGE_CONSTANTS = {
  MAX_TITLE_LENGTH: 500,
  MAX_CONTENT_LENGTH: 10000,
  MAX_ATTACHMENTS: 10,
  MAX_ATTACHMENT_SIZE: 10 * 1024 * 1024 // 10MB
} as const;

export const AGENT_CONSTANTS = {
  MAX_NAME_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_WORKSPACE_PATH_LENGTH: 500,
  MAX_CAPABILITIES: 50,
  MAX_TAGS: 20,
  SESSION_MINUTES_MIN: 1,
  SESSION_MINUTES_MAX: 240
} as const;

export const RATE_LIMIT_CONSTANTS = {
  DEFAULT_REQUESTS_PER_MINUTE: 100,
  DEFAULT_REQUESTS_PER_HOUR: 1000,
  DEFAULT_BURST_SIZE: 10,
  BLOCK_DURATION: 15 * 60 * 1000, // 15 minutes
  WINDOW_SIZE: 60 * 1000 // 1 minute
} as const;

export const MONITORING_CONSTANTS = {
  HEALTH_CHECK_INTERVAL: 30000, // 30 seconds
  METRICS_COLLECTION_INTERVAL: 60000, // 1 minute
  PERFORMANCE_THRESHOLD: 1000, // 1 second
  ERROR_RATE_THRESHOLD: 0.1, // 10%
  MEMORY_THRESHOLD: 0.8 // 80%
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
} as const;

export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
} as const;

/**
 * Application constants
 */

export const SERVER_CONSTANTS = {
  DEFAULT_SESSION_MINUTES: 30,
  MAX_MESSAGES_PER_REQUEST: 500,
  MAX_AGENTS_PER_REQUEST: 100,
  DEFAULT_RATE_LIMIT: 100,
  RATE_LIMIT_WINDOW_MS: 60000 // 1 minute
} as const;


